# Generated by Django 2.2.4 on 2019-10-10 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Congrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Genea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Personaggio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('px_tot', models.IntegerField(default=1)),
                ('px_liberi', models.IntegerField(default=1)),
                ('vigore', models.IntegerField(default=1)),
                ('destrezza', models.IntegerField(default=1)),
                ('psiche', models.IntegerField(default=1)),
                ('percezione', models.IntegerField(default=1)),
                ('nefesh', models.IntegerField(default=1)),
                ('persuasione', models.IntegerField(default=1)),
                ('aetas', models.IntegerField(default=1)),
                ('canal', models.IntegerField(default=1)),
                ('voluntas', models.IntegerField(default=1)),
                ('raptus', models.IntegerField(default=1)),
                ('carica', models.CharField(max_length=30)),
                ('congrega', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Congrega', to='client.Congrega')),
                ('genea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Genea', to='client.Genea')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
