# Generated by Django 2.2.4 on 2019-10-10 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20191010_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congrega',
            options={'verbose_name_plural': 'Congreghe'},
        ),
        migrations.AlterModelOptions(
            name='genea',
            options={'verbose_name_plural': 'Genee'},
        ),
        migrations.AlterModelOptions(
            name='personaggio',
            options={'verbose_name_plural': 'Personaggi'},
        ),
        migrations.RenameField(
            model_name='congrega',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='genea',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='personaggio',
            old_name='nome',
            new_name='name',
        ),
    ]
