# Generated by Django 2.2.4 on 2019-10-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20191010_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaggio',
            name='armi_bianche',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='armi_fuoco',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='atletica',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='manualita',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='sopravvivenza',
            field=models.IntegerField(default=1),
        ),
    ]
