# Generated by Django 2.2.4 on 2019-10-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20191010_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaggio',
            name='accademiche',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='alleati',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='alta_societa',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='criminalita',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='discepoli',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='economia',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='essenza',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='essenza_c',
            field=models.IntegerField(default=1, verbose_name='Essenza corrente'),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='finanza',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='forze_ordine',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='gregge',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='legge',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='media',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='mentore',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='occultismo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='politica',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='religione',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='retaggio',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='risorse',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='ritualistica',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='sanita',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='strada',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='trasporti',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='voluntas_c',
            field=models.IntegerField(default=1, verbose_name='Voluntas corrente'),
        ),
    ]
