# Generated by Django 2.2.4 on 2019-10-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20191010_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaggio',
            name='png',
            field=models.BooleanField(default=False),
        ),
    ]
