# Generated by Django 2.2.4 on 2019-10-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20191011_0757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poterepersonaggiorel',
            options={'verbose_name_plural': 'Poteri'},
        ),
        migrations.AlterModelOptions(
            name='pregiopersonaggiorel',
            options={'verbose_name_plural': 'Pregi e Difetti'},
        ),
        migrations.AddField(
            model_name='personaggio',
            name='dichiarazione',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='personaggio',
            name='carica',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
