# Generated by Django 2.2.4 on 2019-10-11 08:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20191011_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecManualita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('livello', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('personaggio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Personaggio')),
            ],
            options={
                'verbose_name_plural': 'Specializzazione manualita',
            },
        ),
    ]
