# Generated by Django 2.2.4 on 2019-10-11 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0010_specmanualita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giocatore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Giocatori',
            },
        ),
        migrations.AlterField(
            model_name='personaggio',
            name='giocatore',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.Giocatore'),
        ),
    ]
