# Generated by Django 2.2.4 on 2019-10-11 11:11

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_auto_20191011_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaggio',
            name='secret',
            field=models.CharField(default=client.models.md5secret, max_length=32, unique=True),
        ),
    ]
