# Generated by Django 2.2.4 on 2019-10-11 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_personaggio_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaggio',
            name='giocatore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.Giocatore'),
        ),
    ]
