# Generated by Django 2.2.4 on 2019-10-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_auto_20191011_1114'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guadagnopx',
            unique_together={('evento', 'personaggio')},
        ),
        migrations.AlterUniqueTogether(
            name='poterepersonaggiorel',
            unique_together={('potere', 'personaggio')},
        ),
        migrations.AlterUniqueTogether(
            name='pregiopersonaggiorel',
            unique_together={('pregio', 'personaggio')},
        ),
        migrations.AlterUniqueTogether(
            name='specmanualita',
            unique_together={('name', 'personaggio')},
        ),
        migrations.AlterUniqueTogether(
            name='spesapx',
            unique_together={('evento', 'personaggio')},
        ),
    ]
