# Generated by Django 2.2.4 on 2019-10-11 12:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_auto_20191011_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaggio',
            name='aetas_base',
            field=models.SmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='guadagnopx',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Guadagni', to='client.Evento'),
        ),
        migrations.AlterField(
            model_name='guadagnopx',
            name='personaggio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Guadagni', to='client.Personaggio'),
        ),
        migrations.AlterField(
            model_name='guadagnopx',
            name='px_fissi',
            field=models.SmallIntegerField(default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='poterepersonaggiorel',
            name='livello',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='poterepersonaggiorel',
            name='personaggio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Poteri', to='client.Personaggio'),
        ),
        migrations.AlterField(
            model_name='poterepersonaggiorel',
            name='potere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Personaggi', to='client.Potere'),
        ),
        migrations.AlterField(
            model_name='pregiopersonaggiorel',
            name='personaggio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pregi', to='client.Personaggio'),
        ),
        migrations.AlterField(
            model_name='pregiopersonaggiorel',
            name='pregio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Personaggi', to='client.PregioDifetto'),
        ),
        migrations.AlterField(
            model_name='specmanualita',
            name='personaggio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SpecManualita', to='client.Personaggio'),
        ),
        migrations.AlterField(
            model_name='spesapx',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Spese', to='client.Evento'),
        ),
        migrations.AlterField(
            model_name='spesapx',
            name='personaggio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Spese', to='client.Personaggio'),
        ),
    ]
