# Generated by Django 2.2.4 on 2019-10-11 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_auto_20191011_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giocatore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='giocatore', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guadagnopx',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guadagni', to='client.Evento'),
        ),
        migrations.AlterField(
            model_name='guadagnopx',
            name='personaggio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guadagni', to='client.Personaggio'),
        ),
        migrations.AlterField(
            model_name='personaggio',
            name='congrega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='congrega', to='client.Congrega'),
        ),
        migrations.AlterField(
            model_name='personaggio',
            name='genea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genea', to='client.Genea'),
        ),
        migrations.AlterField(
            model_name='poterepersonaggiorel',
            name='personaggio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poteri', to='client.Personaggio'),
        ),
        migrations.AlterField(
            model_name='poterepersonaggiorel',
            name='potere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personaggi', to='client.Potere'),
        ),
        migrations.AlterField(
            model_name='pregiopersonaggiorel',
            name='personaggio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregi', to='client.Personaggio'),
        ),
        migrations.AlterField(
            model_name='pregiopersonaggiorel',
            name='pregio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personaggi', to='client.PregioDifetto'),
        ),
        migrations.AlterField(
            model_name='specmanualita',
            name='personaggio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_manualita', to='client.Personaggio'),
        ),
        migrations.AlterField(
            model_name='spesapx',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spese', to='client.Evento'),
        ),
        migrations.AlterField(
            model_name='spesapx',
            name='personaggio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spese', to='client.Personaggio'),
        ),
    ]
